### ISSUE TITLE
Move to Silex 1.2

### ISSUE THREAD

**Issue by cristianp6** [csanquer/PdoServiceProvider#4]
Hi Charles,
is there any chance to remove the dependency on Silex 1.1 and move onto Silex "dev-master"?

Tnx!

**Comment by csanquer** [comment]
Hi Cristian,

Sorry I was very busy on subjects other than PHP these days.
I 'm going back to work on this library very soon.

But if you have time, create a PR and i will check it.

Thx.

**Comment by csanquer** [comment]
Composer configuration updated.

**Comment by cristianp6** [comment]
Works fine!
Many thanks!
